version: "3.1"
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-config/:/opt/keycloak/data/import/

  eureka-server:
    image: diennt-eureka-server:latest
    ports:
      - "8761:8761"

  spring-cloud-gateway-keycloak-oauth2:
    image: diennt-gateway:latest
    ports:
      - "9090:9090"