
server:
  port: 8761
#
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        defaultZone: http://localhost:8761/eureka/
#
logging:
    level:
      org:
        springframework:
          security:
            web: DEBUG
          hibernate: ERROR
    file:
      name: logs/application-debug.log
      max-size: 2MB
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"